[package]
name = "jsonwebkey"
version = "0.0.2"
authors = ["Nick Hynes <nhynes@nhynes.com>"]
description = "JSON Web Key (JWK) (de)serialization, generation, and conversion."
readme = "README.md"
repository = "https://github.com/nhynes/jwk-rs"
license = "MIT"
edition = "2018"

[dependencies]
base64 = "0.12"
bitflags = "1.2"
derive_more = "0.99"
paste = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
syn = { version = "1.0", features = ["full"] } # required to parse const generics
thiserror = "1.0"
yasna = { version = "0.3", optional = true }
zeroize = { version = "1.1", features = ["zeroize_derive"] }

[features]
conversion = ["yasna"]
